### ISSUE TITLE
Setup a Patreon

### ISSUE THREAD

**Issue by steelbrain** [MichaelFedora/reql-sqlite3#1]
Hello 👋 

Do you have a Patreon or could you set one up? I'm willing to fund the development of ReQL on Postgres. Let me know if that sounds like something you'd also be interested in!

Cheers

**Comment by MichaelFedora** [comment]
Hey @steelbrain ! I'd love to do that, I'll update you here once I get something set up.

**Comment by MichaelFedora** [comment]
@steelbrain you can find it here: https://www.patreon.com/michaelfedora

**Comment by steelbrain** [comment]
Done! Looking forward to your work on reql on pg, thanks again!
